### ISSUE TITLE
ctrl + wheel zoom not working

### ISSUE THREAD

**Issue by spokeydokeys** [luke-rmaki/rmaki-obsidian#1]
I'm having trouble with zooming.  The theme looks great and works otherwise, but neither ctrl + wheel nor ctrl + +/- changes the font size.  With other themes I am able to change the font size using either of these methods.  Any idea what could be causing this?  Great theme, I'm enjoying it a lot.

**Comment by luke-rmaki** [comment]
> I'm having trouble with zooming. The theme looks great and works otherwise, but neither ctrl + wheel nor ctrl + +/- changes the font size. With other themes I am able to change the font size using either of these methods. Any idea what could be causing this? Great theme, I'm enjoying it a lot.

Hey, so sorry for taking so long to get to this.

Which OS and Obsidian version are you using? For me (running Linux and Obsidian v0.14.12) Ctrl +/= and Ctrl -/_ zoom in and out.

Thanks
